#!/usr/bin/env python3
"""Phase 10 Slice D — wrap admin handler hardcoded Cyrillic with texts.t + fa.json."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FA_PATH = ROOT / "app/localization/locales/fa.json"

CYR = re.compile(r"[А-Яа-яЁё]{3,}")


def load_fa() -> dict:
    return json.loads(FA_PATH.read_text(encoding="utf-8"))


def save_fa(data: dict) -> None:
    FA_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def add_keys(fa: dict, keys: dict[str, str]) -> int:
    added = 0
    for k, v in keys.items():
        if k not in fa:
            fa[k] = v
            added += 1
        elif fa[k] != v and CYR.search(fa[k]):
            fa[k] = v
    return added


def count_hardcoded(path: Path) -> int:
    lines = path.read_text(encoding="utf-8").splitlines()
    in_doc = False
    count = 0
    for line in lines:
        s = line.strip()
        if '"""' in s or "'''" in s:
            in_doc = not in_doc
            continue
        if in_doc:
            continue
        if "texts.t" in line or "logger." in line or s.startswith("#"):
            continue
        if CYR.search(line):
            count += 1
    return count


# --- D1 fa keys (Persian) ---
D1_FA: dict[str, str] = {
    "ADMIN_RW_YES": "بله",
    "ADMIN_RW_NO": "خیر",
    "ADMIN_RW_XRAY_RUNNING": "در حال اجرا",
    "ADMIN_RW_XRAY_STOPPED": "متوقف",
    "ADMIN_RW_NO_LIMIT": "بدون سقف",
    "ADMIN_RW_ACTIVE": "✅ فعال",
    "ADMIN_RW_INACTIVE": "❌ غیرفعال",
    "ADMIN_RW_CONNECTED": "📡 بله",
    "ADMIN_RW_NOT_CONNECTED": "📵 خیر",
    "ADMIN_RW_DISABLED_YES": "❌ بله",
    "ADMIN_RW_DISABLED_NO": "✅ خیر",
    "ADMIN_RW_TRAFFIC_ERROR": "❌ خطا در دریافت آمار حجم: {error}",
    "ADMIN_RW_TRAFFIC_STATS_TITLE": "📊 <b>آمار حجم Remnawave</b>",
    "ADMIN_RW_TRAFFIC_INBOUND": "⚡ <b>حجم بر اساس inbound:</b>",
    "ADMIN_RW_TRAFFIC_DOWNLOAD": "- دانلود: {value}",
    "ADMIN_RW_TRAFFIC_UPLOAD": "- آپلود: {value}",
    "ADMIN_RW_TRAFFIC_TOTAL": "- حجم کل: {value}",
    "ADMIN_RW_TRAFFIC_ONLINE": "- کاربران آنلاین: {count}",
    "ADMIN_RW_TRAFFIC_PERIODS": "📈 <b>آمار دوره‌ای:</b>",
    "ADMIN_RW_TRAFFIC_PERIOD_2D": "<b>۲ روز:</b>",
    "ADMIN_RW_TRAFFIC_PERIOD_7D": "<b>۷ روز:</b>",
    "ADMIN_RW_TRAFFIC_PERIOD_30D": "<b>۳۰ روز:</b>",
    "ADMIN_RW_TRAFFIC_PERIOD_MONTH": "<b>ماه جاری:</b>",
    "ADMIN_RW_TRAFFIC_PERIOD_YEAR": "<b>سال جاری:</b>",
    "ADMIN_RW_TRAFFIC_CURRENT": "- فعلی: {value}",
    "ADMIN_RW_TRAFFIC_PREVIOUS": "- قبلی: {value}",
    "ADMIN_RW_TRAFFIC_CHANGE": "- تغییر:{change}",
    "ADMIN_RW_TRAFFIC_NODES_RT": "\n🌐 <b>حجم سرورها (لحظه‌ای):</b>\n",
    "ADMIN_RW_TRAFFIC_NODE_LINE": "- {name}: {value}\n",
    "ADMIN_RW_TRAFFIC_TOP_NODES": "\n📊 <b>برترین سرورها (۷ روز):</b>\n",
    "ADMIN_RW_TRAFFIC_TOP_LINE": "{rank}. {name}: {value}\n",
    "ADMIN_RW_TRAFFIC_UPDATED": "\n🕒 <b>به‌روزرسانی:</b> {time}",
    "ADMIN_RW_BTN_NODES": "📈 سرورها",
    "ADMIN_RW_BTN_SYSTEM": "📊 سیستم",
    "ADMIN_RW_NODES_ONLINE": "👥 آنلاین: {count}\n\n",
    "ADMIN_RW_BTN_RESTART_ALL": "🔄 راه‌اندازی مجدد همه",
    "ADMIN_RW_NODE_DETAIL_TITLE": "🖥️ <b>سرور: {name}</b>",
    "ADMIN_RW_NODE_STATUS_HEADER": "<b>وضعیت:</b>",
    "ADMIN_RW_NODE_ONLINE": "- آنلاین: {emoji} {value}",
    "ADMIN_RW_NODE_XRAY": "- Xray: {emoji} {value}",
    "ADMIN_RW_NODE_CONNECTED": "- متصل: {value}",
    "ADMIN_RW_NODE_DISABLED": "- غیرفعال: {value}",
    "ADMIN_RW_NODE_STATUS_CHANGE": "- تغییر وضعیت: {time}",
    "ADMIN_RW_NODE_MESSAGE": "- پیام: {message}",
    "ADMIN_RW_NODE_XRAY_UPTIME": "- Uptime Xray: {uptime}",
    "ADMIN_RW_NODE_VERSIONS": "<b>نسخه‌ها:</b>",
    "ADMIN_RW_NODE_XRAY_VER": "- Xray: {version}",
    "ADMIN_RW_NODE_VER": "- Node: {version}",
    "ADMIN_RW_NODE_INFO": "<b>اطلاعات:</b>",
    "ADMIN_RW_NODE_ADDRESS": "- آدرس: {address}",
    "ADMIN_RW_NODE_COUNTRY": "- کشور: {code}",
    "ADMIN_RW_NODE_USERS": "- کاربران آنلاین: {count}",
    "ADMIN_RW_NODE_CPU": "- CPU: {info}",
    "ADMIN_RW_NODE_RAM": "- RAM: {ram}",
    "ADMIN_RW_NODE_PROVIDER": "- ارائه‌دهنده: {provider}",
    "ADMIN_RW_NODE_TRAFFIC_HEADER": "<b>حجم:</b>",
    "ADMIN_RW_NODE_TRAFFIC_USED": "- مصرف‌شده: {value}",
    "ADMIN_RW_NODE_TRAFFIC_LIMIT": "- سقف: {value}",
    "ADMIN_RW_NODE_TRACKING": "- ردیابی: {value}",
    "ADMIN_RW_NODE_RESET_DAY": "- روز بازنشانی: {day}",
    "ADMIN_RW_NODE_NOTIFY": "- اعلان‌ها: {percent}",
    "ADMIN_RW_NODE_MULTIPLIER": "- ضریب: {value}",
    "ADMIN_RW_NODE_META": "<b>متاداده:</b>",
    "ADMIN_RW_NODE_CREATED": "- ایجاد: {time}",
    "ADMIN_RW_NODE_UPDATED": "- به‌روز: {time}",
    "ADMIN_RW_NODE_ACTION_ENABLE": "فعال شد",
    "ADMIN_RW_NODE_ACTION_DISABLE": "غیرفعال شد",
    "ADMIN_RW_NODE_ACTION_RESTART": "راه‌اندازی مجدد شد",
    "ADMIN_RW_NODE_ACTION_DEFAULT": "پردازش شد",
    "ADMIN_RW_NODE_STATS_TITLE": "📊 <b>آمار سرور: {name}</b>",
    "ADMIN_RW_NODE_RESOURCES": "<b>منابع:</b>",
    "ADMIN_RW_NODE_LOAD": "- Load: {value}",
    "ADMIN_RW_NODE_INBOUND_RT": "<b>حجم inbound:</b>",
    "ADMIN_RW_NODE_RT_DOWNLOAD": "- دانلود: {value}",
    "ADMIN_RW_NODE_RT_UPLOAD": "- آپلود: {value}",
    "ADMIN_RW_NODE_RT_TOTAL": "- حجم کل: {value}",
    "ADMIN_RW_NODE_RT_ONLINE": "- آنلاین: {count}",
    "ADMIN_RW_NODE_STATS_7D": "\n<b>آمار ۷ روز:</b>\n",
    "ADMIN_RW_NODE_STATS_DAY": "- {date}: {value}\n",
    "ADMIN_RW_NODE_STATS_7D_TOTAL": "\n<b>حجم کل ۷ روز:</b> {value}",
    "ADMIN_RW_NODE_STATS_NO_DATA": "\n<b>آمار ۷ روز:</b> داده در دسترس نیست",
    "ADMIN_RW_BTN_RETRY": "🔄 تلاش مجدد",
    "ADMIN_RW_NODE_STATS_ERROR_TITLE": "⚠️ <b>آمار جزئی موقتاً در دسترس نیست</b>",
    "ADMIN_RW_NODE_STATS_ERROR_BODY": "دلایل احتمالی:\n• مشکل اتصال API\n• سرور تازه اضافه شده\n• داده کافی برای نمایش نیست",
    "ADMIN_RW_SQUAD_NOT_FOUND": "❌ سرور یافت نشد",
    "ADMIN_RW_SQUAD_TITLE": "🌐 <b>سرور: {name}</b>",
    "ADMIN_RW_SQUAD_INFO": "<b>اطلاعات:</b>",
    "ADMIN_RW_SQUAD_UUID": "- UUID: <code>{uuid}</code>",
    "ADMIN_RW_SQUAD_MEMBERS": "- اعضا: {count}",
    "ADMIN_RW_SQUAD_INBOUNDS": "- اینباندها: {count}",
    "ADMIN_RW_SQUAD_INBOUNDS_HEADER": "<b>اینباندها:</b>",
    "ADMIN_RW_SQUAD_INBOUND_LINE": "- {tag} ({type})\n",
    "ADMIN_RW_SQUAD_NO_INBOUNDS": "اینباند فعالی نیست",
    "ADMIN_RW_SQUAD_ADD_USERS_OK": "✅ افزودن کاربران به صف اضافه شد",
    "ADMIN_RW_SQUAD_ADD_USERS_FAIL": "❌ خطا در افزودن کاربران",
    "ADMIN_RW_SQUAD_REMOVE_USERS_OK": "✅ حذف کاربران از صف اضافه شد",
    "ADMIN_RW_SQUAD_REMOVE_USERS_FAIL": "❌ خطا در حذف کاربران",
    "ADMIN_RW_SQUAD_DELETED": "✅ سرور با موفقیت حذف شد",
    "ADMIN_RW_SQUAD_DELETE_FAIL": "❌ خطا در حذف سرور",
    "ADMIN_RW_BTN_TO_SQUADS": "⬅️ به سرورها",
    "ADMIN_RW_SQUAD_EDIT_TITLE": "✏️ <b>ویرایش سرور: {name}</b>",
    "ADMIN_RW_SQUAD_CURRENT_INBOUNDS": "<b>اینباندهای فعلی:</b>",
    "ADMIN_RW_SQUAD_INBOUND_SELECTED": "✅ {tag} ({type})\n",
    "ADMIN_RW_SQUAD_ACTIONS": "\n<b>عملیات موجود:</b>",
    "ADMIN_RW_SQUAD_INBOUND_EDIT_TITLE": "🔧 <b>تغییر اینباندها</b>",
    "ADMIN_RW_SQUAD_LABEL": "<b>سرور:</b> {name}",
    "ADMIN_RW_SQUAD_INBOUND_COUNT": "<b>اینباندهای فعلی:</b> {count}",
    "ADMIN_RW_SQUAD_INBOUND_SELECTED_COUNT": "<b>انتخاب‌شده:</b> {count}",
    "ADMIN_RW_SQUAD_INBOUND_AVAILABLE": "<b>اینباندهای موجود:</b>",
    "ADMIN_RW_SQUAD_INBOUND_LIMIT": "\n⚠️ ۱۵ مورد اول از {total} اینباند نمایش داده شد",
    "ADMIN_RW_BTN_SAVE": "💾 ذخیره تغییرات",
    "ADMIN_RW_INBOUND_NOT_FOUND": "❌ اینباند یافت نشد",
    "ADMIN_RW_INBOUND_REMOVED": "➖ حذف شد: {tag}",
    "ADMIN_RW_INBOUND_ADDED": "➕ افزوده شد: {tag}",
    "ADMIN_RW_SQUAD_UNKNOWN": "نامشخص",
    "ADMIN_RW_SQUAD_INBOUNDS_UPDATED": "✅ <b>اینباندهای سرور به‌روز شد</b>\n\n<b>سرور:</b> {name}\n<b>تعداد اینباند:</b> {count}",
    "ADMIN_RW_SQUAD_INBOUNDS_SAVED": "✅ تغییرات ذخیره شد!",
    "ADMIN_RW_SQUAD_INBOUNDS_SAVE_FAIL": "❌ خطا در ذخیره تغییرات",
    "ADMIN_RW_SQUAD_INBOUNDS_SAVE_ERR": "❌ خطا هنگام ذخیره",
    "ADMIN_RW_SQUAD_RENAME_TITLE": "✏️ <b>تغییر نام سرور</b>",
    "ADMIN_RW_SQUAD_CURRENT_NAME": "<b>نام فعلی:</b> {name}",
    "ADMIN_RW_SQUAD_RENAME_PROMPT": "📝 <b>نام جدید سرور را وارد کنید:</b>",
    "ADMIN_RW_SQUAD_RENAME_RULES": "<i>الزامات نام:</i>\n• ۲ تا ۲۰ کاراکتر\n• فقط حروف، اعداد، خط تیره و زیرخط\n• بدون فاصله و نماد خاص",
    "ADMIN_RW_SQUAD_RENAME_HINT": "نام جدید را بفرستید یا «لغو» را بزنید.",
    "ADMIN_RW_SQUAD_RENAME_ERR": "❌ خطا: سرور یافت نشد",
    "ADMIN_RW_SQUAD_NAME_EMPTY": "❌ نام نمی‌تواند خالی باشد. دوباره تلاش کنید:",
    "ADMIN_RW_SQUAD_NAME_LENGTH": "❌ نام باید ۲ تا ۲۰ کاراکتر باشد. دوباره تلاش کنید:",
    "ADMIN_RW_SQUAD_NAME_CHARS": "❌ نام فقط حروف، اعداد، خط تیره و زیرخط. دوباره تلاش کنید:",
    "ADMIN_RW_SQUAD_NAME_SAME": "❌ نام جدید با فعلی یکسان است. نام دیگری وارد کنید:",
    "ADMIN_RW_SQUAD_RENAME_OK": "✅ <b>نام سرور تغییر کرد!</b>\n\n<b>نام قبلی:</b> {old}\n<b>نام جدید:</b> {new}",
    "ADMIN_RW_BTN_SQUAD_DETAIL": "📋 جزئیات سرور",
    "ADMIN_RW_SQUAD_RENAME_FAIL": "❌ <b>خطا در تغییر نام</b>\n\nدلایل احتمالی:\n• سرور با این نام وجود دارد\n• مشکل اتصال API\n• دسترسی کافی نیست\n\nنام دیگری امتحان کنید:",
    "ADMIN_RW_SQUAD_CREATE_TITLE": "➕ <b>ایجاد سرور جدید</b>",
    "ADMIN_RW_SQUAD_CREATE_STEP1": "<b>مرحله ۱ از ۲: نام سرور</b>",
    "ADMIN_RW_SQUAD_CREATE_NAME_PROMPT": "📝 <b>نام سرور جدید را وارد کنید:</b>",
    "ADMIN_RW_SQUAD_CREATE_STEP2": "<b>مرحله ۲ از ۲: انتخاب اینباند</b>",
    "ADMIN_RW_SQUAD_CREATE_PROGRESS": "➕ <b>ایجاد سرور: {name}</b>",
    "ADMIN_RW_SQUAD_CREATE_SELECTED": "<b>انتخاب‌شده:</b> {count}",
    "ADMIN_RW_BTN_CREATE_SQUAD": "✅ ایجاد سرور",
    "ADMIN_RW_SQUAD_NO_INBOUNDS_CREATE": "❌ <b>اینباند در دسترس نیست</b>\n\nبرای ایجاد سرور حداقل یک اینباند لازم است.",
    "ADMIN_RW_SESSION_ERR": "❌ خطا: داده نشست یافت نشد",
    "ADMIN_RW_SQUAD_SELECT_INBOUND": "❌ حداقل یک اینباند انتخاب کنید",
    "ADMIN_RW_SQUAD_CREATED": "✅ <b>سرور ایجاد شد!</b>\n\n<b>نام:</b> {name}\n<b>تعداد اینباند:</b> {count}\n\nسرور آماده استفاده است!",
    "ADMIN_RW_BTN_SQUAD_LIST": "📋 فهرست سرورها",
    "ADMIN_RW_BTN_TO_RW_PANEL": "⬅️ به پنل Remnawave",
    "ADMIN_RW_SQUAD_CREATED_TOAST": "✅ سرور ایجاد شد!",
    "ADMIN_RW_SQUAD_CREATE_FAIL": "❌ <b>خطا در ایجاد سرور</b>\n\n<b>نام:</b> {name}\n\nدلایل احتمالی:\n• سرور با این نام وجود دارد\n• مشکل اتصال API\n• دسترسی کافی نیست\n• اینباند نامعتبر",
    "ADMIN_RW_SQUAD_CREATE_FAIL_TOAST": "❌ خطا در ایجاد سرور",
    "ADMIN_RW_RESTART_ALL_OK": "✅ دستور راه‌اندازی مجدد همه سرورها ارسال شد",
    "ADMIN_RW_RESTART_ALL_FAIL": "❌ خطا در راه‌اندازی مجدد سرورها",
    "ADMIN_RW_BTN_TO_NODES": "⬅️ به سرورها",
    "ADMIN_RW_SYNC_PANEL_TITLE": "🔄 <b>همگام‌سازی با Remnawave</b>",
    "ADMIN_RW_SYNC_PANEL_BODY": "🔄 <b>همگام‌سازی کامل:</b>\n• ایجاد کاربران جدید پنل در ربات\n• به‌روزرسانی کاربران موجود\n• غیرفعال‌سازی اشتراک‌های غایب در پنل\n• حفظ موجودی کاربران\n• ⏱️ زمان: ۲–۵ دقیقه\n\n⚠️ <b>مهم:</b>\n• در همگام‌سازی عملیات دیگر انجام ندهید\n• اشتراک‌های غایب در پنل غیرفعال می‌شوند\n• روزانه یک‌بار توصیه می‌شود\n• موجودی حذف نمی‌شود\n\n⬆️ <b>همگام‌سازی معکوس:</b>\n• کاربران فعال ربات به پنل ارسال می‌شوند\n• پس از خرابی پنل یا بازیابی داده",
    "ADMIN_RW_SYNC_STATUS_ON": "✅ فعال",
    "ADMIN_RW_SYNC_STATUS_OFF": "❌ غیرفعال",
    "ADMIN_RW_SYNC_STATUS_LINE": "⚙️ وضعیت: {status}",
    "ADMIN_RW_SYNC_SCHEDULE_LINE": "🕒 زمان‌بندی: {times}",
    "ADMIN_RW_SYNC_NEXT_LINE": "📅 اجرای بعدی: {next}",
    "ADMIN_RW_SYNC_LAST_LINE": "📊 آخرین اجرا: {last}",
    "ADMIN_RW_SYNC_LAST_RUNNING": "⏳ شروع {time}",
    "ADMIN_RW_BTN_SYNC_FULL": "🔄 همگام‌سازی کامل",
    "ADMIN_RW_BTN_SYNC_TO_PANEL": "⬆️ همگام‌سازی به پنل",
    "ADMIN_RW_BTN_AUTO_SYNC": "⚙️ تنظیمات همگام‌سازی خودکار",
    "ADMIN_RW_SYNC_SCHEDULE_TITLE": "🕒 <b>تنظیم زمان‌بندی همگام‌سازی خودکار</b>",
    "ADMIN_RW_SYNC_SCHEDULE_BODY": "زمان اجرا را با کاما یا خط جدید به فرمت HH:MM وارد کنید.\nزمان‌بندی فعلی: <code>{schedule}</code>\n\nمثال: <code>03:00, 15:30</code> یا <code>00:15\n06:00\n18:45</code>\n\n<b>لغو</b> بفرستید برای بازگشت بدون تغییر.",
    "ADMIN_RW_SYNC_SCHEDULE_CANCELLED": "تغییر زمان‌بندی لغو شد",
    "ADMIN_RW_SYNC_ALREADY_RUNNING": "همگام‌سازی در حال اجراست",
    "ADMIN_RW_SYNC_STARTING": "🔄 شروع همگام‌سازی خودکار...\n\nلطفاً صبر کنید، ممکن است چند دقیقه طول بکشد.",
    "ADMIN_RW_SYNC_STARTED_TOAST": "همگام‌سازی خودکار شروع شد",
    "ADMIN_RW_SYNC_ALREADY_MSG": "⚠️ <b>همگام‌سازی در حال اجراست</b>\n\n",
    "ADMIN_RW_SYNC_DONE": "✅ <b>همگام‌سازی تمام شد</b>\n👥 کاربران: ایجاد {created}، به‌روز {updated}، غیرفعال {deleted}، خطا {errors}\n🌐 سرورها: ایجاد {s_created}، به‌روز {s_updated}، حذف {s_removed}\n\n",
    "ADMIN_RW_SYNC_FAIL": "❌ <b>همگام‌سازی با خطا پایان یافت</b>\nدلیل: {error}\n\n",
    "ADMIN_RW_SYNC_UNKNOWN_ERR": "خطای نامشخص",
    "ADMIN_RW_SYNC_SCHEDULE_CANCEL_MSG": "تنظیم زمان‌بندی لغو شد",
    "ADMIN_RW_SYNC_TIME_PARSE_FAIL": "❌ زمان شناسایی نشد. فرمت HH:MM مثل 03:00 یا 18:45.",
    "ADMIN_RW_SYNC_SCHEDULE_UPDATED": "✅ زمان‌بندی همگام‌سازی خودکار به‌روز شد",
    "ADMIN_RW_SYNC_FULL_PROGRESS": "🔄 <b>همگام‌سازی کامل در حال اجرا...</b>\n\n📋 مراحل:\n• بارگذاری همه کاربران از پنل\n• ایجاد کاربران جدید\n• به‌روزرسانی موجود\n• غیرفعال‌سازی غایب\n• حفظ موجودی\n\n⏳ لطفاً صبر کنید...",
    "ADMIN_RW_SYNC_STATUS_OK": "با موفقیت تمام شد",
    "ADMIN_RW_SYNC_STATUS_WARN": "با هشدار تمام شد",
    "ADMIN_RW_SYNC_STATUS_ERR": "با خطا تمام شد",
    "ADMIN_RW_SYNC_FULL_RESULT": "{emoji} <b>همگام‌سازی کامل {status}</b>\n\n📊 <b>نتیجه:</b>\n• 🆕 ایجاد: {created}\n• 🔄 به‌روز: {updated}\n• 🗑️ غیرفعال: {deleted}\n• ❌ خطا: {errors}",
    "ADMIN_RW_SYNC_DEACTIVATED_BLOCK": "\n\n🗑️ <b>اشتراک‌های غیرفعال:</b>\nاشتراک کاربران غایب در پنل Remnawave غیرفعال شد.\n💰 موجودی حفظ شد.",
    "ADMIN_RW_SYNC_ERRORS_BLOCK": "\n\n⚠️ <b>توجه:</b>\nبرخی عملیات با خطا پایان یافت.\nلاگ‌ها را بررسی کنید.",
    "ADMIN_RW_SYNC_RECOMMEND": "\n\n💡 <b>توصیه:</b>\n• همگام‌سازی کامل انجام شد\n• روزانه یک‌بار توصیه می‌شود\n• همه کاربران پنل همگام شدند",
    "ADMIN_RW_BTN_RETRY_SYNC": "🔄 تکرار همگام‌سازی",
    "ADMIN_RW_BTN_SYSTEM_STATS": "📊 آمار سیستم",
    "ADMIN_RW_SYNC_TO_PANEL_PROGRESS": "⬆️ همگام‌سازی داده ربات به پنل Remnawave...\n\nممکن است چند دقیقه طول بکشد.",
    "ADMIN_RW_SYNC_TO_PANEL_RESULT": "{emoji} <b>همگام‌سازی به پنل {status}</b>\n\n📊 <b>نتایج:</b>\n• 🆕 ایجاد: {created}\n• 🔄 به‌روز: {updated}\n• ❌ خطا: {errors}",
    "ADMIN_RW_BTN_TO_SYNC": "⬅️ به همگام‌سازی",
    "ADMIN_RW_SYNC_REC_TITLE": "💡 <b>توصیه‌های همگام‌سازی</b>",
    "ADMIN_RW_SYNC_REC_PRIORITY": "{emoji} <b>اولویت:</b> {priority}",
    "ADMIN_RW_SYNC_REC_TIME": "⏱️ <b>زمان تخمینی:</b> {time}",
    "ADMIN_RW_SYNC_REC_ACTION": "<b>عمل پیشنهادی:</b>",
    "ADMIN_RW_SYNC_REC_FULL": "🔄 همگام‌سازی کامل",
    "ADMIN_RW_SYNC_REC_UPDATE": "📈 به‌روزرسانی داده",
    "ADMIN_RW_SYNC_REC_NEW": "🆕 همگام‌سازی جدید",
    "ADMIN_RW_SYNC_REC_NONE": "✅ همگام‌سازی لازم نیست",
    "ADMIN_RW_SYNC_REC_REASONS": "\n<b>دلایل:</b>\n",
    "ADMIN_RW_SYNC_REC_REASON_LINE": "• {reason}\n",
    "ADMIN_RW_BTN_RUN_REC": "✅ اجرای توصیه",
    "ADMIN_RW_BTN_OTHER_SYNC": "🔄 گزینه‌های دیگر",
    "ADMIN_RW_VALIDATE_PROGRESS": "🔍 اعتبارسنجی اشتراک‌ها...\n\nبررسی داده، ممکن است چند دقیقه طول بکشد.",
    "ADMIN_RW_VALIDATE_RESULT": "{emoji} <b>اعتبارسنجی {status}</b>\n\n📊 <b>نتایج:</b>\n• 🔍 بررسی‌شده: {checked}\n• 🔧 اصلاح‌شده: {fixed}\n• ⚠️ مشکل: {issues}\n• ❌ خطا: {errors}",
    "ADMIN_RW_VALIDATE_FIXED": "\n✅ <b>مشکلات اصلاح‌شده:</b>\n• وضعیت منقضی\n• داده Remnawave غایب\n• سقف حجم نامعتبر\n• تنظیمات کاربر\n",
    "ADMIN_RW_VALIDATE_ERRORS": "\n⚠️ خطا در پردازش.\nلاگ‌ها را بررسی کنید.",
    "ADMIN_RW_BTN_RETRY_VALIDATE": "🔄 تکرار اعتبارسنجی",
    "ADMIN_RW_CLEANUP_PROGRESS": "🧹 پاکسازی اشتراک‌های غیرفعال...\n\nحذف اشتراک کاربران غایب در پنل.",
    "ADMIN_RW_CLEANUP_RESULT": "{emoji} <b>پاکسازی {status}</b>\n\n📊 <b>نتایج:</b>\n• 🔍 بررسی: {checked}\n• 🗑️ غیرفعال: {deactivated}\n• ❌ خطا: {errors}",
    "ADMIN_RW_CLEANUP_DEACTIVATED": "\n🗑️ <b>غیرفعال‌شده:</b>\nاشتراک کاربران غایب در پنل Remnawave.\n",
    "ADMIN_RW_CLEANUP_ALL_OK": "\n✅ همه اشتراک‌ها به‌روزند!\nغیرفعالی یافت نشد.",
    "ADMIN_RW_BTN_RETRY_CLEANUP": "🔄 تکرار پاکسازی",
    "ADMIN_RW_BTN_VALIDATE": "🔍 اعتبارسنجی",
    "ADMIN_RW_FORCE_CLEANUP_PROGRESS": "🗑️ پاکسازی اجباری همه کاربران غایب در پنل...\n\n⚠️ هشدار: همه داده کاربران حذف می‌شود!\n📊 شامل: تراکنش، درآمد ارجاع، پروموکد، سرور، موجودی\n\n⏳ لطفاً صبر کنید...",
    "ADMIN_RW_FORCE_CLEANUP_RESULT": "{emoji} <b>پاکسازی اجباری {status}</b>\n\n📊 <b>نتایج:</b>\n• 🔍 بررسی: {checked}\n• 🗑️ پاکسازی کامل: {deactivated}\n• ❌ خطا: {errors}",
    "ADMIN_RW_FORCE_CLEANUP_DETAIL": "\n\n🗑️ <b>داده پاک‌شده:</b>\n• اشتراک به حالت اولیه\n• همه تراکنش‌ها\n• همه درآمد ارجاع\n• استفاده پروموکد\n• موجودی صفر\n• سرورهای متصل\n• HWID در Remnawave\n• UUID Remnawave\n",
    "ADMIN_RW_FORCE_CLEANUP_NONE": "\n✅ غیرفعالی یافت نشد!\nهمه کاربران با پنل همگام‌اند.",
    "ADMIN_RW_SYSTEM_STATS_TITLE": "📊 <b>آمار جزئی Remnawave</b>",
    "ADMIN_RW_SYSTEM_SERVER": "🖥️ <b>سرور:</b>",
    "ADMIN_RW_SYSTEM_CPU": "- CPU: {cores} هسته",
    "ADMIN_RW_SYSTEM_RAM": "- RAM: {used} / {total} ({percent}%)",
    "ADMIN_RW_SYSTEM_FREE": "- آزاد: {free}",
    "ADMIN_RW_SYSTEM_UPTIME": "- Uptime: {uptime}",
    "ADMIN_RW_SYSTEM_USERS": "👥 <b>کاربران ({total} کل):</b>",
    "ADMIN_RW_SYSTEM_ONLINE": "- 🟢 آنلاین: {count}",
    "ADMIN_RW_SYSTEM_DAY": "- 📅 امروز: {count}",
    "ADMIN_RW_SYSTEM_WEEK": "- 📊 این هفته: {count}",
    "ADMIN_RW_SYSTEM_NEVER": "- 💤 هرگز وصل نشده: {count}",
    "ADMIN_RW_SYSTEM_STATUS_HEADER": "<b>وضعیت کاربران:</b>",
    "ADMIN_RW_SYSTEM_NODES": "🌐 <b>سرورها ({online} آنلاین):</b>",
    "ADMIN_RW_SYSTEM_RT": "<b>فعالیت لحظه‌ای:</b>",
    "ADMIN_RW_SYSTEM_RT_LINE": "  📡 {name}: {value}\n",
    "ADMIN_RW_SYSTEM_TOP_WEEK": "<b>برترین سرور (هفته):</b>",
    "ADMIN_RW_SYSTEM_TOP_LINE": "  {rank}. {name}: {value}\n",
    "ADMIN_RW_SYSTEM_USER_TRAFFIC": "\n📈 <b>حجم کل کاربران:</b> {value}",
    "ADMIN_RW_SYSTEM_TRAFFIC_PERIODS": "\n📊 <b>حجم دوره‌ای:</b>",
    "ADMIN_RW_SYSTEM_PERIOD_LINE": "- {label}: {value}{change}",
    "ADMIN_RW_SYSTEM_PERIOD_2D": "۲ روز",
    "ADMIN_RW_SYSTEM_PERIOD_7D": "۷ روز",
    "ADMIN_RW_SYSTEM_PERIOD_30D": "۳۰ روز",
    "ADMIN_RW_SYSTEM_PERIOD_MONTH": "ماه",
    "ADMIN_RW_SYSTEM_PERIOD_YEAR": "سال",
    "ADMIN_RW_SYSTEM_RT_TRAFFIC": "\n⚡ <b>حجم لحظه‌ای:</b>",
    "ADMIN_RW_SYSTEM_RT_DL": "- دانلود: {value}",
    "ADMIN_RW_SYSTEM_RT_UL": "- آپلود: {value}",
    "ADMIN_RW_SYSTEM_RT_TOTAL": "- جمع: {value}",
    "ADMIN_RW_SYSTEM_UPDATED": "\n🕒 <b>به‌روزرسانی:</b> {time}",
    "ADMIN_RW_MEDIA_PHOTO": "عکس",
    "ADMIN_RW_MEDIA_VIDEO": "ویدیو",
}

# Truncated in file — full keys continue in apply functions below
