#!/usr/bin/env python3
"""Apply Phase 10 Slice B Persian translations to cabinet/src/locales/fa.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

FA_PATH = Path(__file__).resolve().parents[1] / 'cabinet' / 'src' / 'locales' / 'fa.json'

# Commit 1: plural forms + misc admin keys (non-banSystem)
SLICE_B1: dict[str, str] = {
    'admin.auditLog.time.daysAgo_one': '{{count}} روز پیش',
    'admin.auditLog.time.hoursAgo_one': '{{count}} ساعت پیش',
    'admin.auditLog.time.minutesAgo_one': '{{count}} دقیقه پیش',
    'admin.auditLog.totalEntries_one': '{{count}} رکورد',
    'admin.broadcasts.channel.both': 'هر دو',
    'admin.broadcasts.channel.email': 'ایمیل',
    'admin.broadcasts.channel.telegram': 'تلگرام',
    'admin.broadcasts.emailSubjectLabel': 'موضوع',
    'admin.broadcasts.filterGroups.email': 'کاربران ایمیل',
    'admin.campaigns.stats.subscriptionsIssued_one': '{{count}} اشتراک',
    'admin.campaigns.stats.tariffsIssued_one': '{{count}} سرویس',
    'admin.campaigns.table.registrations_one': '{{count}} ثبت‌نام',
    'admin.nav.bulkActions': 'عملیات گروهی',
    'admin.policies.conditions.ipCount_one': '{{count}} IP',
    'admin.promoOffers.result.notificationsFailed_one': '(ناموفق: {{count}})',
    'admin.promoOffers.result.notificationsFailed_other': '(ناموفق: {{count}})',
    'admin.promoOffers.result.notificationsSent_one': 'اعلان ارسال شد: {{count}}',
    'admin.promoOffers.result.offersCreated_one': 'پیشنهاد ایجاد شد: {{count}}',
    'admin.promoOffers.tabs.templates_one': 'قالب‌ها ({{count}} قالب)',
    'admin.promocodes.groups.members_one': '{{count}} عضو',
    'admin.promocodes.stats.hoursValue_one': '{{count}} ساعت',
    'admin.promocodes.tabs.groups_one': 'گروه‌های تخفیف ({{count}} گروه)',
    'admin.promocodes.tabs.promocodes_one': 'کدهای تخفیف ({{count}} کد)',
    'admin.remnawave.nodes.usersOnlineCount_one': '{{count}} آنلاین',
    'admin.remnawave.squads.inboundsCount_one': '{{count}} ورودی',
    'admin.remnawave.squads.membersCount_one': '{{count}} عضو',
    'admin.roleAssign.totalAssignments_one': '{{count}} تخصیص در مجموع',
    'admin.roles.form.selectedPermissions_one': '{{count}} مجوز انتخاب شده',
    'admin.roles.permissionsCount_one': '{{count}} مجوز',
    'admin.roles.usersCount_one': '{{count}} کاربر',
    'admin.tariffs.days_one': '{{count}} روز',
    'admin.tariffs.devices_one': '{{count}} کاربر',
    'admin.tariffs.periodDisabled': 'غیرفعال',
    'admin.tariffs.serverTrafficLimit': 'محدودیت حجم',
    'admin.tariffs.servers_one': '{{count}} سرور',
    'admin.tariffs.subscriptions_one': '{{count}} اشتراک',
    'admin.tariffs.useDefault': 'پیش‌فرض',
    'admin.users.purchaseCount_one': '{{count}} خرید',
    'admin.users.userActions.confirmDelete.message': 'مطمئن هستید؟ این عمل غیرقابل بازگشت است. کاربر به‌طور کامل از ربات و پنل Remnawave حذف می‌شود.',
    'admin.users.userActions.confirmDelete.title': 'حذف کاربر؟',
    'admin.users.userActions.confirmDisable.message': 'کاربر تا زمان فعال‌سازی مجدد نمی‌تواند از سرویس استفاده کند.',
    'admin.users.userActions.confirmDisable.title': 'غیرفعال کردن کاربر؟',
    'admin.users.userActions.confirmResetSubscription.message': 'اشتراک فعلی کاربر لغو می‌شود.',
    'admin.users.userActions.confirmResetSubscription.title': 'بازنشانی اشتراک؟',
    'admin.users.userActions.confirmResetTrial.message': 'کاربر دوباره می‌تواند از دوره آزمایشی استفاده کند.',
    'admin.users.userActions.confirmResetTrial.title': 'بازنشانی آزمایشی؟',
    'admin.wheel.statistics.times_one': '{{count}} بار',
    'adminDashboard.nodes.showMore_one': 'نمایش {{count}} گره دیگر',
    'adminDashboard.tariffs.noTariffs': 'سرویسی وجود ندارد',
    'news.admin.combobox.clear': 'پاک کردن',
    'news.admin.combobox.create': 'ایجاد',
    'news.admin.combobox.createNew': 'ایجاد جدید',
    'news.admin.combobox.delete': 'حذف {{name}}',
    'news.admin.combobox.noItems': 'موردی یافت نشد',
    'news.admin.combobox.placeholder': 'انتخاب...',
    'news.admin.combobox.searchOrCreate': 'جستجو یا ایجاد...',
    'news.admin.combobox.selectCategory': 'انتخاب دسته',
    'news.admin.combobox.selectTag': 'انتخاب برچسب',
}

# Commit 2: banSystem missing keys
SLICE_B2: dict[str, str] = {
    'banSystem.agents.batches': 'دسته‌ها',
    'banSystem.agents.dedup': 'حذف تکراری',
    'banSystem.agents.failures': 'خطاها',
    'banSystem.agents.filter': 'فیلتر',
    'banSystem.agents.lastReport': 'آخرین گزارش',
    'banSystem.agents.nodeName': 'گره',
    'banSystem.agents.reconnects': 'اتصال مجدد',
    'banSystem.agents.summary.avgQueueSize': 'میانگین اندازه صف',
    'banSystem.agents.summary.criticalCount': 'بحرانی',
    'banSystem.agents.summary.healthyCount': 'سالم',
    'banSystem.agents.summary.onlineAgents': 'آنلاین',
    'banSystem.agents.summary.title': 'خلاصه',
    'banSystem.agents.summary.totalAgents': 'کل عامل‌ها',
    'banSystem.agents.summary.totalDropped': 'کل حذف‌شده',
    'banSystem.agents.summary.totalSent': 'کل ارسال‌شده',
    'banSystem.agents.summary.warningCount': 'هشدار',
    'banSystem.agents.title': 'عامل‌ها',
    'banSystem.banModal.ban': 'مسدود کردن',
    'banSystem.banModal.cancel': 'لغو',
    'banSystem.banModal.duration': 'مدت (دقیقه)',
    'banSystem.banModal.durationPlaceholder': 'مدت را به دقیقه وارد کنید',
    'banSystem.banModal.error': 'مسدودسازی ناموفق بود',
    'banSystem.banModal.reason': 'دلیل',
    'banSystem.banModal.reasonPlaceholder': 'دلیل مسدودسازی (اختیاری)',
    'banSystem.banModal.success': 'کاربر مسدود شد',
    'banSystem.banModal.title': 'مسدود کردن کاربر',
    'banSystem.banModal.username': 'نام کاربری',
    'banSystem.banModal.usernamePlaceholder': 'نام کاربری را وارد کنید',
    'banSystem.dashboard.activePunishments': 'مسدودسازی‌های فعال',
    'banSystem.dashboard.activeUsers': 'کاربران فعال',
    'banSystem.dashboard.agentsOnline': 'عامل‌های آنلاین',
    'banSystem.dashboard.nodesOnline': 'گره‌های آنلاین',
    'banSystem.dashboard.panelConnected': 'پنل متصل',
    'banSystem.dashboard.panelDisconnected': 'پنل قطع',
    'banSystem.dashboard.totalPunishments': 'کل مسدودسازی‌ها',
    'banSystem.dashboard.totalRequests': 'کل درخواست‌ها',
    'banSystem.dashboard.totalUsers': 'کل کاربران',
    'banSystem.dashboard.uptime': 'زمان فعالیت',
    'banSystem.dashboard.usersOverLimit': 'بیش از حد',
    'banSystem.health.components': 'اجزا',
    'banSystem.health.degraded': 'تضعیف‌شده',
    'banSystem.health.healthy': 'سالم',
    'banSystem.health.title': 'سلامت سیستم',
    'banSystem.health.unhealthy': 'ناسالم',
    'banSystem.health.uptime': 'زمان فعالیت',
    'banSystem.nodes.address': 'آدرس',
    'banSystem.nodes.lastSeen': 'آخرین بازدید',
    'banSystem.nodes.name': 'نام',
    'banSystem.nodes.onlineCount': 'آنلاین',
    'banSystem.nodes.title': 'گره‌ها',
    'banSystem.nodes.total': 'کل',
    'banSystem.nodes.usersCount': 'کاربران',
    'banSystem.punishments.actions': 'عملیات',
    'banSystem.punishments.history': 'تاریخچه مسدودسازی',
    'banSystem.punishments.noHistory': 'تاریخچه‌ای یافت نشد',
    'banSystem.punishments.noPunishments': 'مسدودسازی فعالی نیست',
    'banSystem.punishments.node': 'گره',
    'banSystem.punishments.punishedAt': 'زمان مسدودسازی',
    'banSystem.punishments.searchHistory': 'جستجو در تاریخچه...',
    'banSystem.punishments.title': 'مسدودسازی‌های فعال',
    'banSystem.punishments.unbanConfirm': 'رفع مسدودسازی {{username}}؟',
    'banSystem.punishments.unbanError': 'رفع مسدودسازی ناموفق بود',
    'banSystem.punishments.unbanSuccess': 'مسدودسازی کاربر رفع شد',
    'banSystem.punishments.username': 'کاربر',
    'banSystem.reports.title': 'گزارش‌های دوره‌ای',
    'banSystem.settings.categories.general': 'تنظیمات عمومی',
    'banSystem.settings.categories.network': 'شناسایی شبکه',
    'banSystem.settings.categories.notifications': 'اعلان‌ها',
    'banSystem.settings.categories.progressive_bans': 'مسدودسازی تصاعدی',
    'banSystem.settings.categories.punishment': 'مسدودسازی‌ها',
    'banSystem.settings.categories.rate_limit': 'محدودیت نرخ',
    'banSystem.settings.categories.traffic': 'نظارت ترافیک',
    'banSystem.settings.daily_report_enabled': 'گزارش روزانه',
    'banSystem.settings.daily_report_hour': 'ساعت گزارش',
    'banSystem.settings.error': 'خطا در ذخیره',
    'banSystem.settings.general': 'عمومی',
    'banSystem.settings.heartbeat_timeout': 'مهلت heartbeat (ثانیه)',
    'banSystem.settings.ip_window_seconds': 'پنجره شمارش IP (ثانیه)',
    'banSystem.settings.limits': 'محدودیت‌ها',
    'banSystem.settings.network_block_mobile': 'مسدود کردن موبایل',
    'banSystem.settings.network_block_mobile_minutes': 'مسدود کردن موبایل (دقیقه)',
    'banSystem.settings.network_block_wifi': 'مسدود کردن WiFi',
    'banSystem.settings.network_block_wifi_minutes': 'مسدود کردن WiFi (دقیقه)',
    'banSystem.settings.network_detection_collect_all': 'جمع‌آوری از همه گره‌ها',
    'banSystem.settings.network_detection_enabled': 'شناسایی نوع شبکه',
    'banSystem.settings.network_detection_monitor_all': 'نظارت بر همه گره‌ها',
    'banSystem.settings.network_detection_nodes': 'گره‌های شناسایی',
    'banSystem.settings.network_notify_mobile': 'اعلان در موبایل',
    'banSystem.settings.network_notify_wifi': 'اعلان در WiFi',
    'banSystem.settings.notifications': 'اعلان‌ها',
    'banSystem.settings.notify_on_node_status': 'اعلان وضعیت گره',
    'banSystem.settings.notify_on_punishment': 'اعلان مسدودسازی',
    'banSystem.settings.progressive_ban_1': 'مسدودسازی اول (دقیقه)',
    'banSystem.settings.progressive_ban_2': 'مسدودسازی دوم (دقیقه)',
    'banSystem.settings.progressive_ban_3': 'مسدودسازی سوم (دقیقه)',
    'banSystem.settings.progressive_ban_window_hours': 'پنجره بازنشانی (ساعت)',
    'banSystem.settings.progressive_bans_enabled': 'مسدودسازی تصاعدی',
    'banSystem.settings.punishment_enabled': 'فعال‌سازی مسدودسازی خودکار',
    'banSystem.settings.punishment_minutes': 'مدت مسدودسازی (دقیقه)',
    'banSystem.settings.rate_limit_max': 'حداکثر درخواست',
    'banSystem.settings.rate_limit_window': 'پنجره محدودیت نرخ (ثانیه)',
    'banSystem.settings.saved': 'تنظیم ذخیره شد',
    'banSystem.settings.title': 'تنظیمات سیستم',
    'banSystem.settings.traffic_ban_minutes': 'مسدودسازی ترافیک (دقیقه)',
    'banSystem.settings.traffic_check_interval': 'فاصله بررسی (دقیقه)',
    'banSystem.settings.traffic_limit_gb': 'محدودیت ترافیک (گیگ)',
    'banSystem.settings.traffic_monitor_enabled': 'نظارت ترافیک',
    'banSystem.settings.traffic_window_minutes': 'پنجره بررسی (دقیقه)',
    'banSystem.settings.whitelist': 'لیست سفید',
    'banSystem.traffic.title': 'آمار ترافیک',
    'banSystem.userDetail.action': 'عملیات',
    'banSystem.userDetail.ban': 'مسدود کردن',
    'banSystem.userDetail.city': 'شهر',
    'banSystem.userDetail.close': 'بستن',
    'banSystem.userDetail.destination': 'مقصد',
    'banSystem.userDetail.email': 'ایمیل',
    'banSystem.userDetail.firstSeen': 'اولین بازدید',
    'banSystem.userDetail.lastSeen': 'آخرین بازدید',
    'banSystem.userDetail.limit': 'محدودیت کاربر',
    'banSystem.userDetail.networkType': 'نوع شبکه',
    'banSystem.userDetail.noIps': 'داده IP وجود ندارد',
    'banSystem.userDetail.noRequests': 'داده درخواست وجود ندارد',
    'banSystem.userDetail.port': 'پورت',
    'banSystem.userDetail.protocol': 'پروتکل',
    'banSystem.userDetail.recentRequests': 'درخواست‌های اخیر',
    'banSystem.userDetail.requestCount': 'درخواست‌ها',
    'banSystem.userDetail.sourceIp': 'IP مبدأ',
    'banSystem.userDetail.status': 'وضعیت',
    'banSystem.userDetail.timestamp': 'زمان',
    'banSystem.userDetail.totalRequests': 'کل درخواست‌ها',
    'banSystem.userDetail.uniqueIps': 'IP یکتا',
    'banSystem.users.filter.all': 'همه',
    'banSystem.users.filter.normal': 'عادی',
    'banSystem.users.filter.overLimit': 'بیش از حد',
    'banSystem.users.lastSeen': 'آخرین بازدید',
    'banSystem.users.noLimit': 'بدون محدودیت',
    'banSystem.users.noUsers': 'کاربری یافت نشد',
    'banSystem.users.normal': 'عادی',
    'banSystem.users.requests': 'درخواست‌ها',
    'banSystem.users.title': 'کاربران',
    'banSystem.users.uniqueIps': 'IP یکتا',
    'banSystem.violations.bytesLimit': 'محدودیت',
    'banSystem.violations.bytesUsed': 'مصرف‌شده',
    'banSystem.violations.email': 'ایمیل',
    'banSystem.violations.no': 'خیر',
    'banSystem.violations.title': 'تخلفات ترافیک',
    'banSystem.violations.username': 'کاربر',
    'banSystem.violations.yes': 'بله',
}

# Commit 3: English-leak fixes in existing fa admin keys
SLICE_B3: dict[str, str] = {
    'admin.pinnedMessages.title': 'پیام‌های سنجاق‌شده',
    'admin.pinnedMessages.subtitle': 'مدیریت پیام‌های سنجاق‌شده برای کاربران',
    'admin.pinnedMessages.create': 'ایجاد',
    'admin.pinnedMessages.empty': 'پیام سنجاق‌شده‌ای وجود ندارد',
    'admin.pinnedMessages.content': 'متن پیام',
    'admin.pinnedMessages.contentPlaceholder': 'متن پیام سنجاق‌شده را وارد کنید...',
    'admin.pinnedMessages.noContent': 'بدون متن',
    'admin.pinnedMessages.media': 'فایل رسانه',
    'admin.pinnedMessages.addMedia': 'افزودن رسانه',
    'admin.pinnedMessages.uploading': 'در حال آپلود...',
    'admin.pinnedMessages.settings': 'تنظیمات',
    'admin.pinnedMessages.sendBeforeMenu': 'ارسال قبل از منو',
    'admin.pinnedMessages.sendOnEveryStart': 'ارسال در هر شروع',
    'admin.pinnedMessages.broadcast': 'پیام‌رسانی',
    'admin.pinnedMessages.broadcastOnCreate': 'پیام‌رسانی هنگام ایجاد',
    'admin.pinnedMessages.broadcastConfirm': 'پیام سنجاق‌شده برای همه کاربران فعال ارسال شود؟',
    'admin.pinnedMessages.broadcastToAll': 'ارسال به همه',
    'admin.pinnedMessages.activate': 'فعال‌سازی',
    'admin.pinnedMessages.deactivate': 'غیرفعال‌سازی',
    'admin.pinnedMessages.unpin': 'برداشتن سنجاق',
    'admin.pinnedMessages.unpinAll': 'برداشتن سنجاق برای همه',
    'admin.pinnedMessages.unpinConfirm': 'سنجاق پیام برای همه کاربران برداشته شود؟',
    'admin.pinnedMessages.delete': 'حذف',
    'admin.pinnedMessages.deleteConfirm': 'این پیام سنجاق‌شده حذف شود؟',
    'admin.pinnedMessages.active': 'فعال',
    'admin.pinnedMessages.inactive': 'غیرفعال',
    'admin.pinnedMessages.prev': 'قبلی',
    'admin.pinnedMessages.next': 'بعدی',
    'admin.pinnedMessages.createSuccess': 'پیام سنجاق‌شده ایجاد شد',
    'admin.pinnedMessages.updateSuccess': 'پیام به‌روزرسانی شد',
    'admin.pinnedMessages.deleteSuccess': 'پیام حذف شد',
    'admin.pinnedMessages.activateSuccess': 'پیام فعال شد',
    'admin.pinnedMessages.deactivateSuccess': 'پیام غیرفعال شد',
    'admin.pinnedMessages.broadcastSuccess': 'پیام‌رسانی انجام شد',
    'admin.pinnedMessages.unpinSuccess': 'سنجاق پیام‌ها برداشته شد',
    'admin.pinnedMessages.sentCount': 'ارسال‌شده',
    'admin.pinnedMessages.failedCount': 'ناموفق',
    'admin.pinnedMessages.unpinnedCount': 'برداشته‌شده',
    'admin.pinnedMessages.editMessage': 'ویرایش',
    'admin.pinnedMessages.cantDeleteActive': 'پیام فعال را نمی‌توان حذف کرد',
    'admin.policies.conditions.ipCount_other': '{{count}} IP',
}


def set_nested(data: dict[str, Any], path: str, value: str) -> None:
    parts = path.split('.')
    current = data
    for part in parts[:-1]:
        current = current.setdefault(part, {})
    current[parts[-1]] = value


def apply_slice(data: dict[str, Any], translations: dict[str, str]) -> int:
    for path, value in translations.items():
        set_nested(data, path, value)
    return len(translations)


def main() -> None:
    slice_name = sys.argv[1] if len(sys.argv) > 1 else 'all'
    slices = {
        'b1': SLICE_B1,
        'b2': SLICE_B2,
        'b3': SLICE_B3,
        'all': {**SLICE_B1, **SLICE_B2, **SLICE_B3},
    }
    if slice_name not in slices:
        raise SystemExit(f'Usage: {sys.argv[0]} [b1|b2|b3|all]')

    data = json.loads(FA_PATH.read_text(encoding='utf-8'))
    count = apply_slice(data, slices[slice_name])
    FA_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(f'Applied {count} translations ({slice_name}) to {FA_PATH}')


if __name__ == '__main__':
    main()
